<ul id="menu">
	<li><a href="index.php">HOME</a></li>
	<li><a href="schedule.php">SCHEDULE</a></li>
    <li>RESULTS
        <ul>
            <li><a href="leaguetable-sw.php">SOUTH WEST</a></li>
            <li><a href="leaguetable-m.php">MIDLANDS</a></li>
            <li><a href="leaguetable-se.php">LONDON &amp; SE</a></li>
            <li><a href="leaguetable-n.php">NORTHERN</a></li>
            <li><a href="leaguetable-sc.php">SCOTTISH</a></li>
            <li><a href="leaguetable-ir.php">IRISH</a></li>
            <li><a href="finals.php">FINALS</a></li>
            <li><a href="placings.php">MEET WINNERS</a></li>
            <li><a href="winners.php">LEAGUE WINNERS</a></li>
        </ul>
    </li>
    <li><a href="rankings.php">RANKINGS</a></li>
    <li>HI SCORES
        <ul>
            <li><a href="highaveragescores.php">HI/AVG SCORES</a></li>
            <li><a href="highscores10.php">HI SCORES 10</a></li>
            <li><a href="highscoresperplayer.php">HI PER PLAYER</a></li>
        </ul>
    </li>
    
    <li>RULES/FAQ
        <ul>
            <li><a href="rules.php">RULES</a></li>
            <li><a href="faq.php">FAQ</a></li>
        </ul>
    </li>
    <li><a href="links.php">LINKS</a></li>
    <li><a href="contacts.php">CONTACTS</a></li>
</ul>