<ul id="menu">
	<li><a href="index.php">HOME</a></li>
	<li><a href="schedule.php">SCHEDULE</a></li>
    <li>RESULTS
        <ul>
            <li><a href="league.php?region=sw">SOUTH WEST</a></li>
            <li><a href="league.php?region=m">MIDLANDS</a></li>
            <li><a href="league.php?region=lse">LONDON &amp; SE</a></li>
            <li><a href="league.php?region=n">NORTHERN</a></li>
            <li><a href="league.php?region=s">SCOTTISH</a></li>
            <li><a href="league.php?region=i">IRISH</a></li>
            <li><a href="league.php?region=ea">EAST ANGLIA</a></li>
            <li><a href="finals.php">FINALS</a></li>
            <li><a href="placings.php">MEET WINNERS</a></li>
            <li><a href="winners.php">LEAGUE WINNERS</a></li>
        </ul>
    </li>
    <li><a href="rankings.php">RANKINGS</a></li>
    <li><a href="machines.php">MACHINES</a></li>
    
    <li>RULES/FAQ
        <ul>
            <li><a href="rules.php">RULES</a></li>
            <li><a href="faq.php">FAQ</a></li>
        </ul>
    </li>
    <li><a href="links.php">LINKS</a></li>
    <li><a href="contacts.php">CONTACTS</a></li>
</ul>